[centos:vars]
ansible_private_key_file=/home/p0mi/.ssh/key.pem
ansible_user=admin

[kafka]
192.168.1.18 ansible_user=root
[kafka_test:vars]
ansible_user=admin
ansible_private_key_file=/home/p0mi/.ssh/key.pem

[kafka_test]
kafka1 ansible_host=192.168.1.21 BROKER_ID=1
kafka2 ansible_host=192.168.1.16 BROKER_ID=2
kafka3 ansible_host=192.168.1.22 BROKER_ID=3

[oracle]
192.169.3.37 ansible_user=root

[centos]
centos1 ansible_host=192.168.1.20