<<<<<<< Updated upstream
[oracle]
192.169.3.37 ansible_user=root
=======
[ubus:vars]
ansible_private_key_file=/home/arsen/.ssh/key.pem
ansible_user=admin

[ubus]
ubu1 ansible_host=192.168.3.5 BROKER_ID=1
ubu2 ansible_host=192.168.3.11 BROKER_ID=2
ubu3 ansible_host=192.168.3.12 BROKER_ID=3

[centos]
192.168.3.16 ansible_private_key_file=/home/arsen/.ssh/key.pem ansible_user=admin
>>>>>>> Stashed changes
