server {
    listen 80;
    server_name test.local;  # Или localhost, если нужно
    return 301 https://$host$request_uri;  # Редирект с HTTP на HTTPS
}

server {
    listen 443 ssl;
    server_name test.local;  # Должно совпадать с CN в сертификате

    # Пути к SSL-сертификату и ключу
    ssl_certificate /etc/ssl/test.local/test.local.crt;
    ssl_certificate_key /etc/ssl/test.local/test.local.key;

    # Настройки SSL
    ssl_protocols TLSv1.2 TLSv1.3;  # Отключаем устаревшие протоколы
    ssl_prefer_server_ciphers on;
    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384";
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location /front/ {
        alias /etc/nginx/html/front/;
        try_files $uri $uri/ /index.html;
    }

    location /gitea/ {
        proxy_pass http://gitea:3000/;  # Gitea по умолчанию слушает 3000 порт
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Для Web-интерфейса Gitea
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
    }



        location /jenkins/ {
        proxy_pass http://jenkins:8080/jenkins/;  # Gitea по умолчанию слушает 3000 порт
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}